'use client';
import {useEffect,useState} from 'react';
import {supabaseBrowser} from '../../../lib/supabase';
import {useRouter} from 'next/navigation';
import * as XLSX from 'xlsx';

type Student={id:string;admission_no:string;name:string;class_name:string;section:string;parent_name:string;parent_phone:string;area:string|null;sibling_group:string|null;hostel_required:boolean;vehicle_required:boolean;vehicle_area:string|null;student_status:string};
const empty={admission_no:'',name:'',class_name:'',section:'A',parent_name:'',parent_phone:'',area:'',sibling_group:'',hostel_required:false,vehicle_required:false,vehicle_area:''};
const val=(r:Record<string,unknown>, keys:string[])=>{for(const k of keys){if(r[k]!==undefined&&r[k]!==null&&String(r[k]).trim()!=='')return String(r[k]).trim()}return ''};
export default function Students(){
 const getSb=()=>supabaseBrowser(); const router=useRouter(); const [rows,setRows]=useState<Student[]>([]); const [f,setF]=useState(empty); const [importing,setImporting]=useState(false); const [search,setSearch]=useState('');
 async function load(){const {data,error}=await getSb().from('students').select('*').order('class_name').order('name');if(error)alert(error.message);setRows((data||[]) as Student[])}
 useEffect(()=>{getSb().auth.getUser().then(({data:{user}})=>{if(!user)router.push('/login');else load()})},[]);
 async function add(e:React.FormEvent){e.preventDefault();const payload={...f,admission_no:f.admission_no.trim(),name:f.name.trim(),class_name:f.class_name.trim(),section:f.section.trim()||'A',parent_name:f.parent_name.trim(),parent_phone:f.parent_phone.trim(),area:f.area.trim()||null,sibling_group:f.sibling_group.trim()||null,vehicle_area:f.vehicle_required?(f.vehicle_area.trim()||null):null};const {error}=await getSb().from('students').insert(payload);if(error)alert(error.message);else{setF(empty);load()}}
 async function importExcel(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setImporting(true);try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'});const sheet=wb.Sheets[wb.SheetNames[0]];const data=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:''});const mapped=data.map(r=>({admission_no:val(r,['admission_no','Admission No','AdmissionNo']),name:val(r,['name','Name','Student Name']),class_name:val(r,['class_name','Class','Class Name']),section:val(r,['section','Section'])||'A',parent_name:val(r,['parent_name','Parent Name','Parent']),parent_phone:val(r,['parent_phone','Parent Phone','Phone']),area:val(r,['area','Area']),sibling_group:val(r,['sibling_group','Sibling Group','Family ID']),hostel_required:['yes','true','1'].includes(val(r,['hostel_required','Hostel','Hostel Student']).toLowerCase()),vehicle_required:['yes','true','1'].includes(val(r,['vehicle_required','Vehicle','Transport']).toLowerCase()),vehicle_area:val(r,['vehicle_area','Vehicle Area','Route'])||null})).filter(r=>r.admission_no&&r.name&&r.class_name&&r.parent_name&&r.parent_phone);if(!mapped.length)throw new Error('No valid rows found. Admission No, Name, Class, Parent Name and Parent Phone are required.');const {error}=await getSb().from('students').upsert(mapped,{onConflict:'admission_no'});if(error)throw error;alert(`${mapped.length} student records imported/updated successfully. Existing admission numbers were updated.`);load()}catch(err:any){alert(err.message||'Excel import failed.')}finally{setImporting(false);e.target.value=''}}
 function template(){const data=[{admission_no:'AES001',name:'Rahul Kumar',class_name:'VIII',section:'A',parent_name:'Raj Kumar',parent_phone:'9876543210',area:'Laukahi',sibling_group:'FAM001',hostel_required:'No',vehicle_required:'Yes',vehicle_area:'Route A'}];const ws=XLSX.utils.json_to_sheet(data);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Students');XLSX.writeFile(wb,'admission-student-template.xlsx')}
 const filtered=rows.filter(s=>`${s.name} ${s.admission_no} ${s.class_name} ${s.parent_name} ${s.sibling_group||''}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="admin"><aside className="side"><h2>Admin Portal</h2><a href="/admin">Dashboard</a><a href="/admin/students">Students</a><a href="/admin/fees">Fees</a><a href="/admin/fee-structure">Fee Structure</a><a href="/admin/notices">Notice Board</a><a href="/notices">Public Website</a></aside><section className="main"><h1>Students & Sibling Groups</h1><p className="muted">Parents have no portal access. Student records are maintained only by school staff.</p>
 <div className="card"><h3>Add student</h3><form onSubmit={add} className="grid"><input className="input" placeholder="Admission No" value={f.admission_no} onChange={e=>setF({...f,admission_no:e.target.value})} required/><input className="input" placeholder="Student Name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><input className="input" placeholder="Class" value={f.class_name} onChange={e=>setF({...f,class_name:e.target.value})} required/><input className="input" placeholder="Section" value={f.section} onChange={e=>setF({...f,section:e.target.value})} required/><input className="input" placeholder="Parent Name" value={f.parent_name} onChange={e=>setF({...f,parent_name:e.target.value})} required/><input className="input" placeholder="Parent Phone" value={f.parent_phone} onChange={e=>setF({...f,parent_phone:e.target.value})} required/><input className="input" placeholder="Student Area" value={f.area} onChange={e=>setF({...f,area:e.target.value})}/><input className="input" placeholder="Sibling/Family Group ID (e.g. FAM001)" value={f.sibling_group} onChange={e=>setF({...f,sibling_group:e.target.value})}/><label className="check"><input type="checkbox" checked={f.hostel_required} onChange={e=>setF({...f,hostel_required:e.target.checked})}/> Hostel student</label><label className="check"><input type="checkbox" checked={f.vehicle_required} onChange={e=>setF({...f,vehicle_required:e.target.checked})}/> Uses school vehicle</label>{f.vehicle_required&&<input className="input" placeholder="Vehicle Area / Route" value={f.vehicle_area} onChange={e=>setF({...f,vehicle_area:e.target.value})}/>}<button className="btn dark" type="submit">Add Student</button></form></div><br/>
 <div className="card"><h3>Excel import / update</h3><p className="muted">Upload the template. If <b>admission_no</b> already exists, that student is <b>updated</b>; otherwise a new student is created. This lets you maintain all 500 records from Excel.</p><button className="btn" onClick={template}>Download Excel Template</button><input className="input" type="file" accept=".xlsx,.xls" onChange={importExcel} disabled={importing}/>{importing&&<p>Importing and updating…</p>}</div><br/>
 <div className="card"><div className="top"><h3>Student register ({filtered.length})</h3><input className="input" style={{maxWidth:320}} placeholder="Search student, admission, class, sibling group" value={search} onChange={e=>setSearch(e.target.value)}/></div><table className="table"><thead><tr><th>Admission</th><th>Name</th><th>Class</th><th>Parent</th><th>Area</th><th>Sibling Group</th><th>Hostel</th><th>Vehicle</th></tr></thead><tbody>{filtered.map(s=><tr key={s.id}><td>{s.admission_no}</td><td>{s.name}</td><td>{s.class_name}-{s.section}</td><td>{s.parent_name}<br/><span className="muted">{s.parent_phone}</span></td><td>{s.area||'—'}</td><td>{s.sibling_group||'—'}</td><td>{s.hostel_required?'Yes':'No'}</td><td>{s.vehicle_required?s.vehicle_area||'Yes':'No'}</td></tr>)}</tbody></table></div>
 </section></div>
}
