'use client';
import {useEffect,useState} from 'react';import {supabaseBrowser} from '../../../lib/supabase';import {useRouter} from 'next/navigation';import {jsPDF} from 'jspdf';

type Student={id:string;name:string;admission_no:string;class_name:string;section:string;hostel_required:boolean;vehicle_required:boolean;vehicle_area:string|null;sibling_group:string|null};
type Charge={id:string;student_id:string;fee_head:string;amount:number;frequency:string;period:string|null;due_date:string|null;notes:string|null};
type Structure={id:string;class_name:string;fee_head:string;amount:number;frequency:string;hostel_only:boolean;vehicle_area:string|null};
export default function Fees(){
 const getSb=()=>supabaseBrowser();const router=useRouter();const [students,setStudents]=useState<Student[]>([]);const [structures,setStructures]=useState<Structure[]>([]);const [charges,setCharges]=useState<Charge[]>([]);const [rows,setRows]=useState<any[]>([]);const [studentId,setStudentId]=useState('');const [chargeId,setChargeId]=useState('');const [amount,setAmount]=useState('');const [customHead,setCustomHead]=useState('');const [search,setSearch]=useState('');const [loading,setLoading]=useState(false);
 async function load(){const sb=getSb();const [{data:s},{data:p},{data:fs},{data:c}]=await Promise.all([sb.from('students').select('id,name,admission_no,class_name,section,hostel_required,vehicle_required,vehicle_area,sibling_group').eq('student_status','active').order('name'),sb.from('fee_payments').select('*,students(name,admission_no,class_name,section)').order('created_at',{ascending:false}),sb.from('fee_structures').select('*').order('class_name'),sb.from('student_fee_charges').select('*').order('created_at',{ascending:false})]);setStudents((s||[]) as Student[]);setRows(p||[]);setStructures((fs||[]) as Structure[]);setCharges((c||[]) as Charge[])}
 useEffect(()=>{getSb().auth.getUser().then(({data:{user}})=>{if(!user)router.push('/login');else load()})},[]);
 const student=students.find(s=>s.id===studentId);const studentCharges=charges.filter(c=>c.student_id===studentId);const paidByCharge=new Map<string,number>();rows.filter(p=>p.status==='paid').forEach(p=>{if(p.student_fee_charge_id)paidByCharge.set(p.student_fee_charge_id,(paidByCharge.get(p.student_fee_charge_id)||0)+Number(p.amount))});
 function matchingRules(s:Student){return structures.filter(r=>{if(r.class_name!==s.class_name)return false;if(r.hostel_only&&!s.hostel_required)return false;if(r.vehicle_area&&(!s.vehicle_required||r.vehicle_area.toLowerCase()!==String(s.vehicle_area||'').toLowerCase()))return false;if(r.fee_head.toLowerCase().includes('hostel')&&!s.hostel_required)return false;if(r.fee_head.toLowerCase().includes('vehicle')&&!s.vehicle_required)return false;return true})}
 async function generateFees(){if(!student)return;setLoading(true);try{const rules=matchingRules(student);if(!rules.length)throw new Error('No fee rules match this student. Configure Fee Structure first.');const existing=new Set(studentCharges.map(c=>`${c.fee_head}|${c.amount}|${c.frequency}`));const newCharges=rules.filter(r=>!existing.has(`${r.fee_head}|${r.amount}|${r.frequency}`)).map(r=>({student_id:student.id,fee_head:r.fee_head,amount:Number(r.amount),frequency:r.frequency,notes:r.vehicle_area?`Vehicle area: ${r.vehicle_area}`:r.hostel_only?'Hostel-only fee':null}));if(newCharges.length){const {error}=await getSb().from('student_fee_charges').insert(newCharges);if(error)throw error;alert(`${newCharges.length} applicable fee(s) generated for ${student.name}.`)}else alert('All applicable standard fees are already generated for this student.');await load()}catch(e:any){alert(e.message||'Could not generate fees')}finally{setLoading(false)}}
 function receipt(p:any){const doc=new jsPDF();const date=p.paid_at?new Date(p.paid_at).toLocaleDateString('en-IN'):new Date().toLocaleDateString('en-IN');doc.setFontSize(18);doc.text('ADARSH AVASIYA SCHOOL',105,22,{align:'center'});doc.setFontSize(11);doc.text('OFFICIAL CASH FEE RECEIPT',105,31,{align:'center'});doc.line(20,38,190,38);doc.text(`Receipt No: ${p.receipt_no}`,20,50);doc.text(`Date: ${date}`,140,50);doc.text(`Student: ${p.students?.name||''}`,20,63);doc.text(`Admission No: ${p.students?.admission_no||''}`,20,74);doc.text(`Class: ${p.students?.class_name||''}-${p.students?.section||''}`,20,85);doc.text(`Fee Head: ${p.fee_head}`,20,102);doc.text(`Amount Paid: Rs. ${Number(p.amount).toLocaleString('en-IN')}`,20,114);doc.text('Payment Mode: CASH',20,125);doc.line(20,136,190,136);doc.text('Received in cash at the school office.',20,151);doc.text('Thank you for your payment.',20,161);doc.save(`${p.receipt_no}.pdf`)}
 async function pay(e:React.FormEvent){e.preventDefault();if(!studentId||!chargeId||!amount)return;const charge=studentCharges.find(c=>c.id===chargeId);if(!charge)return;const already=paidByCharge.get(charge.id)||0;const due=Math.max(0,Number(charge.amount)-already);if(Number(amount)>due){alert(`Payment cannot exceed remaining due of ₹${due.toLocaleString('en-IN')}.`);return}setLoading(true);const {data,error}=await getSb().from('fee_payments').insert({student_id:studentId,student_fee_charge_id:chargeId,fee_head:charge.fee_head,amount:Number(amount),status:'paid',payment_mode:'cash',paid_at:new Date().toISOString(),notes:charge.period?`Period: ${charge.period}`:null}).select('*,students(name,admission_no,class_name,section)').single();setLoading(false);if(error)alert(error.message);else{receipt(data);setAmount('');setChargeId('');await load()}}
 async function addCustom(e:React.FormEvent){e.preventDefault();if(!studentId||!customHead||!amount)return;const {error}=await getSb().from('student_fee_charges').insert({student_id:studentId,fee_head:customHead,amount:Number(amount),frequency:'One-time',notes:'Student-specific charge'});if(error)alert(error.message);else{setCustomHead('');setAmount('');alert('Student-specific charge added.');load()}}
 const filteredRows=rows.filter(p=>`${p.students?.name||''} ${p.students?.admission_no||''} ${p.fee_head}`.toLowerCase().includes(search.toLowerCase()));
 const selectedCharge=studentCharges.find(c=>c.id===chargeId);const selectedDue=selectedCharge?Math.max(0,Number(selectedCharge.amount)-(paidByCharge.get(selectedCharge.id)||0)):0;
 return <div className="admin"><aside className="side"><h2>Admin Portal</h2><a href="/admin">Dashboard</a><a href="/admin/students">Students</a><a href="/admin/fees">Fees</a><a href="/admin/fee-structure">Fee Structure</a><a href="/admin/notices">Notice Board</a></aside><section className="main"><h1>Cash Fee Management</h1><p className="muted">Admin-only collection. Parents have no portal access. All payments are recorded as CASH.</p>
 <div className="card"><h3>1. Select student</h3><select className="input" value={studentId} onChange={e=>{setStudentId(e.target.value);setChargeId('');setAmount('')}}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} — {s.admission_no} — Class {s.class_name}-{s.section}</option>)}</select>{student&&<div className="info"><b>{student.name}</b> · {student.class_name}-{student.section} · Family/Sibling: {student.sibling_group||'Not assigned'} · Hostel: {student.hostel_required?'Yes':'No'} · Vehicle: {student.vehicle_required?(student.vehicle_area||'Yes'):'No'}<br/><button className="btn dark" onClick={generateFees} disabled={loading}>Generate Applicable Fees</button></div>}</div><br/>
 {student&&<div className="card"><h3>2. Student fee ledger</h3><p className="muted">Standard fees are generated from class rules. Hostel and vehicle charges are added only when applicable.</p><table className="table"><thead><tr><th>Fee</th><th>Amount</th><th>Paid</th><th>Due</th><th>Frequency</th><th></th></tr></thead><tbody>{studentCharges.map(c=>{const paid=paidByCharge.get(c.id)||0;const due=Math.max(0,Number(c.amount)-paid);return <tr key={c.id}><td>{c.fee_head}<br/><span className="muted">{c.notes||''}</span></td><td>₹{Number(c.amount).toLocaleString('en-IN')}</td><td>₹{paid.toLocaleString('en-IN')}</td><td className={due?'danger':'success'}>₹{due.toLocaleString('en-IN')}</td><td>{c.frequency}</td><td>{due>0&&<button className="btn" onClick={()=>{setChargeId(c.id);setAmount(String(due))}}>Collect</button>}</td></tr>})}</tbody></table></div>}
 <br/><div className="card"><h3>3. Collect cash</h3><form onSubmit={pay} className="grid"><select className="input" value={chargeId} onChange={e=>{setChargeId(e.target.value);const c=studentCharges.find(x=>x.id===e.target.value);if(c){const due=Math.max(0,Number(c.amount)-(paidByCharge.get(c.id)||0));setAmount(String(due))}}} disabled={!studentId} required><option value="">Select outstanding fee</option>{studentCharges.filter(c=>Number(c.amount)-(paidByCharge.get(c.id)||0)>0).map(c=><option key={c.id} value={c.id}>{c.fee_head} — Due ₹{(Number(c.amount)-(paidByCharge.get(c.id)||0)).toLocaleString('en-IN')}</option>)}</select><input className="input" type="number" min="1" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Cash amount" required/><input className="input" value="CASH ONLY" readOnly/><button className="btn dark" type="submit" disabled={loading||!studentId}>{loading?'Saving…':'Save Cash & Generate Bill'}</button></form>{selectedCharge&&<p className="muted">Remaining due: <b>₹{selectedDue.toLocaleString('en-IN')}</b></p>}</div><br/>
 <div className="card"><h3>Add student-specific charge</h3><p className="muted">Use this for an exceptional amount that is not part of the class fee structure.</p><form onSubmit={addCustom} className="grid"><input className="input" placeholder="Charge name e.g. Special Book Set" value={customHead} onChange={e=>setCustomHead(e.target.value)} required/><input className="input" type="number" min="0" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)} required/><button className="btn dark" type="submit" disabled={!studentId}>Add Charge</button></form></div><br/>
 <div className="card"><div className="top"><h3>Payment history</h3><input className="input" style={{maxWidth:320}} placeholder="Search payment" value={search} onChange={e=>setSearch(e.target.value)}/></div><table className="table"><thead><tr><th>Receipt</th><th>Student</th><th>Fee</th><th>Amount</th><th>Mode</th><th>Date</th><th></th></tr></thead><tbody>{filteredRows.map(p=><tr key={p.id}><td>{p.receipt_no}</td><td>{p.students?.name}</td><td>{p.fee_head}</td><td>₹{Number(p.amount).toLocaleString('en-IN')}</td><td>CASH</td><td>{p.paid_at?new Date(p.paid_at).toLocaleDateString('en-IN'):'—'}</td><td><button className="btn" onClick={()=>receipt(p)}>PDF</button></td></tr>)}</tbody></table></div>
 </section></div>
}
